(function(a,b){if("function"==typeof define&&define.amd)define([],b);else if("undefined"!=typeof exports)b();else{b(),a.index={exports:{}}.exports}})(this,function(){"use strict";function a(a,b,c,d,e,f,g){try{var h=a[f](g),i=h.value}catch(a){return void c(a)}h.done?b(i):Promise.resolve(i).then(d,e)}function b(b){return function(){var c=this,d=arguments;return new Promise(function(e,f){function g(b){a(i,e,f,g,h,"next",b)}function h(b){a(i,e,f,g,h,"throw",b)}var i=b.apply(c,d);g(void 0)})}}function c(a){return a.replace(/\B(?=(\d{2})+(?!\d))/g,",")}function d(a,b,c){let d=[];for(let e=b-1;e<=c-1;e++)d.push(a[e]);return d}function e(){return f.apply(this,arguments)}// eslint-disable-next-line func-names
function f(){return f=b(function*(a,b){// eslint-disable-next-line prefer-const
let e,f,h=g.load(a);if(4>h("body").text().split("|").length)return Promise.resolve(JSON.stringify({err:"Resultado n\xE3o disponivel!",errCode:1}));try{e=h("body").text().split("|")}catch(a){return Promise.reject(JSON.stringify(a))}if("megasena"===b)try{f={numberRaffle:e[0],locationRaffle:`${e[14]},${e[12]},${e[13]}`,unorNumbers:c(e[2]),orderedNumbers:c(e[20]),date:e[11],totalCollection:e[24],// eslint-disable-next-line radix
isAccumulated:0===parseInt(e[3]),sena:{winers:e[3],prizeByWinner:e[4]},quina:{winers:e[5],prizeByWinner:e[6]},quadra:{winers:e[7],prizeByWinner:e[8]},nextRaffle:{date:e[22],estimatedPrize:e[21],accumulated:e[1]},accumulatedMegavirada:e[23]// eslint-disable-next-line semi
}}catch(a){return Promise.reject(JSON.stringify(a))}if("quina"===b)try{console.log(e),f={numberRaffle:e[0],locationRaffle:`${e[4]},${e[2]},${e[3]}`,unorNumbers:d(c(e[14]).split(","),1,5).join(","),orderedNumbers:d(c(e[14]).split(","),6,10).join(","),date:e[16],totalCollection:e[20],// eslint-disable-next-line radix
isAccumulated:0===parseInt(e[6]),quina:{winers:e[6],prizeByWinner:e[7]},quadra:{winers:e[8],prizeByWinner:e[9]},terno:{winers:e[10],prizeByWinner:e[11]},duque:{winers:e[23],prizeByWinner:e[22]},nextRaffle:{date:e[18],estimatedPrize:e[17],accumulated:e[13]},accumulatedSaoJoao:e[21]// eslint-disable-next-line semi
}}catch(a){return Promise.reject(JSON.stringify(a))}if("lotofacil"===b)try{console.log(e,e.length),f={numberRaffle:e[0],locationRaffle:`${e[31]},${e[32]},${e[33]}`,unorNumbers:d(e,39,53).join(","),orderedNumbers:d(e,4,18).join(","),date:e[34],totalCollection:e[55],// eslint-disable-next-line radix
isAccumulated:0===parseInt(e[18]),acertos15:{winers:e[18],prizeByWinner:e[19]},acertos14:{winers:e[20],prizeByWinner:e[21]},acertos13:{winers:e[22],prizeByWinner:e[23]},acertos12:{winers:e[24],prizeByWinner:e[25]},acertos11:{winers:e[26],prizeByWinner:e[27]},nextRaffle:{date:e[54],estimatedPrize:e[53],accumulated:e[56]}// eslint-disable-next-line semi
}}catch(a){return Promise.reject(JSON.stringify(a))}return Promise.resolve(f)}),f.apply(this,arguments)}const g=require("cheerio"),h=require("request-promise");Object.defineProperty(exports,"__esModule",{value:!0}),exports.resultByNumber=/*#__PURE__*/function(){var a=b(function*(a,b){let c;if(b===void 0)try{return c=yield h(`http://www1.caixa.gov.br/loterias/loterias/${a}/${a}_pesquisa_new.asp`,{jar:!0// encoding: 'utf8'
}),yield e(c,a)}catch(a){return Promise.reject(JSON.stringify(a.error))}else try{return c=yield h(`http://www1.caixa.gov.br/loterias/loterias/${a}/${a}_pesquisa_new.asp?submeteu=sim&opcao=concurso&txtConcurso=${b}`,{jar:!0// encoding: 'utf8'
}),yield e(c,a)}catch(a){return Promise.reject(JSON.stringify(a.error))}// eslint-disable-next-line semi
});return function(){return a.apply(this,arguments)}}()});
//# sourceMappingURL=index.js.map